#ifndef CONFIG_H_
#define CONFIG_H_

#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_DISPLAY_WIDTH 64
#define CHIP8_DISPLAY_HEIGHT 32
#define CHIP8_TOTAL_GREGISTERS 16
#define WINDOW_SCALE 15

#endif // CONFIG_H_
